CREATE TABLE AUTH_TODOS(
    ID VARCHAR(255) PRIMARY KEY,
    USER_EMAIL VARCHAR(255),
    TITLE VARCHAR(255),
    PROGRESS INT,
    TODO_DATE VARCHAR(255)
);

CREATE TABLE USERS(
    EMAIL VARCHAR(50) PRIMARY KEY,
    HASHED_PASSWORD VARCHAR(255)
);

SELECT * FROM AUTH_TODOS;
SELECT * FROM USERS;

DELETE FROM AUTH_TODOS
WHERE USER_EMAIL='arqam@user.com';
COMMIT;

DELETE FROM USERS
WHERE EMAIL='test@example.com';
COMMIT;